services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gift_shop_web
    ports:
      - "3006:3006"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
